# Data generation for Rust tests

In [12]:
from sklearn.datasets import make_blobs
from gaussian_mixtures import *
from pathlib import Path

data, z = make_blobs(n_samples=10000, centers=10, n_features=2, random_state=7)  # pylint: disable=W0632
# responsibilities = Likelihood(np.random.dirichlet(10 * [1.0], data.shape[0]))
responsibilities = np.zeros((10000, 10))
responsibilities[np.arange(10000),z] = 1.0
gmm = GaussianMixtureModel(np.zeros(0), np.zeros(0), np.zeros(0))
maximize_(gmm, responsibilities, data)

print(gmm.means)
print(gmm.covs)

path = Path('../rust/data')
np.save(path / "data.npy", data)
np.save(path / "responsibilities.npy", responsibilities)
np.save(path / "means.npy", gmm.means)
np.save(path / "weights.npy", gmm.weights)
np.save(path / "covs.npy", gmm.covs)

print("habemus data")

[[-8.47562951e+00  5.52376622e+00]
 [-1.24282838e+00  4.49286923e+00]
 [ 9.56403650e+00  7.21121629e-01]
 [ 3.06531799e-03 -8.55880638e+00]
 [-4.61737505e+00  3.01849256e-02]
 [ 3.54694152e+00  6.07366732e+00]
 [-2.33641967e+00 -8.75475190e+00]
 [-4.21535030e+00  8.17893066e+00]
 [-5.71958567e+00 -9.81886695e-01]
 [ 8.61379480e+00 -9.50692668e+00]]
[[[ 0.98666553  0.0313411 ]
  [ 0.0313411   0.97141586]]

 [[ 0.97317742  0.03576458]
  [ 0.03576458  0.99419635]]

 [[ 1.02846929 -0.00348803]
  [-0.00348803  0.97742699]]

 [[ 0.94792488  0.03654492]
  [ 0.03654492  1.00066831]]

 [[ 0.89767761  0.00991275]
  [ 0.00991275  1.05951857]]

 [[ 0.91232854  0.03583903]
  [ 0.03583903  0.96693534]]

 [[ 0.94772947  0.02801429]
  [ 0.02801429  0.95383765]]

 [[ 0.99348339  0.00416763]
  [ 0.00416763  0.95085358]]

 [[ 1.02181297 -0.01171953]
  [-0.01171953  0.9734114 ]]

 [[ 0.97452637 -0.04438497]
  [-0.04438497  1.02395777]]]
habemus data


In [8]:
make_blobs?

Signature:
make_blobs(
    n_samples=100,
    n_features=2,
    *,
    centers=None,
    cluster_std=1.0,
    center_box=(-10.0, 10.0),
    shuffle=True,
    random_state=None,
    return_centers=False,
)
Docstring:
Generate isotropic Gaussian blobs for clustering.

For an example of usage, see
:ref:`sphx_glr_auto_examples_datasets_plot_random_dataset.py`.

Read more in the :ref:`User Guide <sample_generators>`.

Parameters
----------
n_samples : int or array-like, default=100
    If int, it is the total number of points equally divided among
    clusters.
    If array-like, each element of the sequence indicates
    the number of samples per cluster.

    .. versionchanged:: v0.20
        one can now pass an array-like to the ``n_samples`` parameter

n_features : int, default=2
    The number of features for each sample.

centers : int or array-like of shape (n_centers, n_features), default=None
    The number of centers to generate, or the fixed center locations.
    If n_samples is 